print("this is a python file")
print("hello world")
print("this is a python file")
print("hello world")
print("this is a python file")
print("hello world")
print("this is a python file")
print("hello world")
